name: Build and Deploy
on: [push]
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
      with:
        # fetch all commits to get last updated time or other git log info
        fetch-depth: 0
          
    # run build script
    - name: Build VuePress site
      run: yarn docs:build
      
    # @see https://github.com/crazy-max/ghaction-github-pages
    - name: Deploy to GitHub Pages
      uses: crazy-max/ghaction-github-pages@v2
      with:
        # deploy to gh-pages branch
        target_branch: gh-pages
        # deploy the default output dir of VuePress
        build_dir: docs/.vuepress/dist
      env:
        # @see https://docs.github.com/en/actions/reference/authentication-in-a-workflow#about-the-github_token-secret
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
